# Dracula colours for the mpv on-screen controller (osc.lua)
#
# See the LICENSE file at the top of the project tree for copyright
# and license details.

background_color=#282a36
timecode_color=#f8f8f2
title_color=#f8f8f2
time_pos_color=#f8f8f2
time_pos_outline_color=#282a36
buttons_color=#bd93f9
top_buttons_color=#bd93f9
small_buttonsL_color=#6272a4
small_buttonsR_color=#6272a4
held_element_color=#ff79c6
boxalpha=80
