# Kakoune configuration
#
# See the LICENSE file at the top of the project tree for copyright
# and license details.

# Dracula theme (shipped in ~/.config/kak/colors/dracula.kak).
colorscheme dracula
